// Firebase Config Placeholder
// const firebaseConfig = {
//   apiKey: "your-api-key",
//   authDomain: "your-project.firebaseapp.com",
//   projectId: "your-project-id",
//   storageBucket: "your-project.appspot.com",
//   messagingSenderId: "your-sender-id",
//   appId: "your-app-id"
// };
// 
// // Initialize Firebase
// firebase.initializeApp(firebaseConfig);
// const auth = firebase.auth();
// const db = firebase.firestore();
// const storage = firebase.storage();

// Mock Services Data (English)
const mockServices = [
    {
        id: 1,
        title: "Generate 50 Instagram Posts",
        price: 400,
        provider: "AI Content Master",
        description: "Create unique and engaging posts for your Instagram account",
        category: "Content",
        image: "instagram"
    },
    {
        id: 2,
        title: "Write 2000-word SEO Article",
        price: 600,
        provider: "SEO Writer Pro",
        description: "Search engine optimized article with keywords and meta tags",
        category: "Copywriting",
        image: "article"
    },
    {
        id: 3,
        title: "AI Logo Design",
        price: 250,
        provider: "Design AI Studio",
        description: "Unique logo for your brand generated by neural networks",
        category: "Design",
        image: "logo"
    },
    {
        id: 4,
        title: "Market & Competitor Analysis",
        price: 800,
        provider: "Market Intelligence",
        description: "Detailed market analysis and competitive landscape report",
        category: "Analytics",
        image: "market"
    },
    {
        id: 5,
        title: "Generate 60-second Video Ad",
        price: 500,
        provider: "Video AI Creator",
        description: "Professional video advertisement for social media platforms",
        category: "Video",
        image: "video"
    },
    {
        id: 6,
        title: "Translate Text to 5 Languages",
        price: 300,
        provider: "Translate AI",
        description: "High-quality translation of your content to 5 popular languages",
        category: "Translation",
        image: "translate"
    },
    {
        id: 7,
        title: "Create Business Plan",
        price: 1000,
        provider: "Business Planner AI",
        description: "Comprehensive business plan for your startup or project",
        category: "Business",
        image: "business"
    },
    {
        id: 8,
        title: "Generate Website Code",
        price: 750,
        provider: "Code Generator Pro",
        description: "Responsive website code based on your requirements",
        category: "Programming",
        image: "code"
    }
];

// DOM Elements
const loginBtn = document.getElementById('loginBtn');
const mobileLoginBtn = document.getElementById('mobileLoginBtn');
const becomeProviderBtn = document.getElementById('becomeProviderBtn');
const mobileBecomeProviderBtn = document.getElementById('mobileBecomeProviderBtn');
const searchServicesBtn = document.getElementById('searchServicesBtn');
const mobileMenuBtn = document.getElementById('mobileMenuBtn');
const closeMobileMenuBtn = document.getElementById('closeMobileMenuBtn');

// Search and Filter Elements
const searchInput = document.getElementById('searchInput');
const categoryFilter = document.getElementById('categoryFilter');
const activeFilters = document.getElementById('activeFilters');
const noResults = document.getElementById('noResults');
const clearFiltersBtn = document.getElementById('clearFilters');

// Modals
const loginModal = document.getElementById('loginModal');
const registerModal = document.getElementById('registerModal');
const addServiceModal = document.getElementById('addServiceModal');
const mobileMenu = document.getElementById('mobileMenu');

// Forms
const loginForm = document.getElementById('loginForm');
const registerForm = document.getElementById('registerForm');
const addServiceForm = document.getElementById('addServiceForm');

// Modal switching buttons
const showRegisterBtn = document.getElementById('showRegisterBtn');
const showLoginBtn = document.getElementById('showLoginBtn');

// Services grid
const servicesGrid = document.getElementById('servicesGrid');

// State
let currentUser = null;
let services = [...mockServices];
let filteredServices = [...services];
let currentFilters = {
    search: '',
    category: 'all'
};

// Initialize app
document.addEventListener('DOMContentLoaded', function() {
    // Initialize Lucide icons
    lucide.createIcons();
    
    // Render services
    renderServices();
    
    // Setup event listeners
    setupEventListeners();
    
    // Check for logged in user (placeholder)
    // auth.onAuthStateChanged(user => {
    //     currentUser = user;
    //     updateUI();
    // });
});

// Setup event listeners
function setupEventListeners() {
    // Navigation buttons
    loginBtn.addEventListener('click', () => openModal(loginModal));
    mobileLoginBtn.addEventListener('click', () => {
        closeModal(mobileMenu);
        openModal(loginModal);
    });
    
    becomeProviderBtn.addEventListener('click', () => {
        if (currentUser) {
            openModal(addServiceModal);
        } else {
            openModal(loginModal);
        }
    });
    
    mobileBecomeProviderBtn.addEventListener('click', () => {
        closeModal(mobileMenu);
        if (currentUser) {
            openModal(addServiceModal);
        } else {
            openModal(loginModal);
        }
    });
    
    searchServicesBtn.addEventListener('click', () => {
        document.getElementById('services').scrollIntoView({ behavior: 'smooth' });
    });
    
    // Mobile menu
    mobileMenuBtn.addEventListener('click', () => openModal(mobileMenu));
    closeMobileMenuBtn.addEventListener('click', () => closeModal(mobileMenu));
    
    // Modal switching
    showRegisterBtn.addEventListener('click', (e) => {
        e.preventDefault();
        closeModal(loginModal);
        openModal(registerModal);
    });
    
    showLoginBtn.addEventListener('click', (e) => {
        e.preventDefault();
        closeModal(registerModal);
        openModal(loginModal);
    });
    
    // Modal close buttons
    document.querySelectorAll('.modal-close').forEach(btn => {
        btn.addEventListener('click', (e) => {
            const modal = e.target.closest('.modal');
            closeModal(modal);
        });
    });
    
    // Modal overlay clicks
    document.querySelectorAll('.modal-overlay').forEach(overlay => {
        overlay.addEventListener('click', (e) => {
            const modal = e.target.closest('.modal');
            closeModal(modal);
        });
    });
    
    // Search and filter functionality
    searchInput.addEventListener('input', debounce(handleSearch, 300));
    categoryFilter.addEventListener('change', handleCategoryFilter);
    clearFiltersBtn.addEventListener('click', clearAllFilters);
    
    // Form submissions
    loginForm.addEventListener('submit', handleLogin);
    registerForm.addEventListener('submit', handleRegister);
    addServiceForm.addEventListener('submit', handleAddService);
    
    // Mobile menu navigation links
    mobileMenu.querySelectorAll('a[href^="#"]').forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const targetId = link.getAttribute('href').substring(1);
            const targetElement = document.getElementById(targetId);
            if (targetElement) {
                closeModal(mobileMenu);
                targetElement.scrollIntoView({ behavior: 'smooth' });
            }
        });
    });
}

// Modal functions
function openModal(modal) {
    if (modal) {
        modal.classList.remove('hidden');
        document.body.style.overflow = 'hidden';
        
        // Reinitialize Lucide icons in modal
        setTimeout(() => {
            lucide.createIcons();
        }, 100);
    }
}

function closeModal(modal) {
    if (modal) {
        modal.classList.add('hidden');
        document.body.style.overflow = '';
    }
}

// Render services
function renderServices() {
    if (!servicesGrid) return;
    
    servicesGrid.innerHTML = '';
    
    services.forEach(service => {
        const serviceCard = createServiceCard(service);
        servicesGrid.appendChild(serviceCard);
    });
    
    // Reinitialize Lucide icons
    lucide.createIcons();
}

// Create service card
function createServiceCard(service) {
    const card = document.createElement('div');
    card.className = 'service-card';
    
    card.innerHTML = `
        <div class="service-image">
            <div class="flex items-center justify-center h-full">
                <i data-lucide="${getServiceIcon(service.category)}" class="w-12 h-12 text-blue-400"></i>
            </div>
        </div>
        <div class="service-content">
            <h3 class="service-title">${service.title}</h3>
            <div class="service-price">${service.price} UAH</div>
            <div class="service-provider">Provider: ${service.provider}</div>
            <button class="service-order-btn" data-service-id="${service.id}">
                Order Now
            </button>
        </div>
    `;
    
    // Add click event to order button
    const orderBtn = card.querySelector('.service-order-btn');
    orderBtn.addEventListener('click', () => handleOrderService(service));
    
    return card;
}

// Get service icon based on category
function getServiceIcon(category) {
    const icons = {
        'Content': 'image',
        'Copywriting': 'file-text',
        'Design': 'palette',
        'Analytics': 'bar-chart',
        'Video': 'video',
        'Translation': 'languages',
        'Business': 'briefcase',
        'Programming': 'code'
    };
    return icons[category] || 'cpu';
}

// Handle service order
function handleOrderService(service) {
    if (!currentUser) {
        openModal(loginModal);
        return;
    }
    
    // Placeholder for order functionality
    alert(`Ordering service: ${service.title}\nPrice: ${service.price} UAH\n\nIn a real app, this would open the order process.`);
}

// Handle login
function handleLogin(e) {
    e.preventDefault();
    
    const email = e.target.querySelector('input[type="email"]').value;
    const password = e.target.querySelector('input[type="password"]').value;
    
    // Placeholder for Firebase authentication
    // auth.signInWithEmailAndPassword(email, password)
    //   .then(userCredential => {
    //     currentUser = userCredential.user;
    //     updateUI();
    //     closeModal(loginModal);
    //   })
    //   .catch(error => {
    //     console.error('Login error:', error);
    //     alert('Помилка входу: ' + error.message);
    //   });
    
    // Mock login for demo
    console.log('Login attempt:', { email, password });
    currentUser = { email, displayName: 'Demo User' };
    updateUI();
    closeModal(loginModal);
    e.target.reset();
}

// Handle registration
function handleRegister(e) {
    e.preventDefault();
    
    const email = e.target.querySelector('input[type="email"]').value;
    const password = e.target.querySelector('input[type="password"]').value;
    const role = e.target.querySelector('input[name="role"]:checked').value;
    
    // Placeholder for Firebase authentication
    // auth.createUserWithEmailAndPassword(email, password)
    //   .then(userCredential => {
    //     currentUser = userCredential.user;
    //     // Save user role to Firestore
    //     return db.collection('users').doc(userCredential.user.uid).set({
    //       email,
    //       role,
    //       createdAt: firebase.firestore.FieldValue.serverTimestamp()
    //     });
    //   })
    //   .then(() => {
    //     updateUI();
    //     closeModal(registerModal);
    //   })
    //   .catch(error => {
    //     console.error('Registration error:', error);
    //     alert('Помилка реєстрації: ' + error.message);
    //   });
    
    // Mock registration for demo
    console.log('Registration attempt:', { email, password, role });
    currentUser = { email, displayName: 'Demo User', role };
    updateUI();
    closeModal(registerModal);
    e.target.reset();
}

// Handle add service
function handleAddService(e) {
    e.preventDefault();
    
    const title = document.getElementById('serviceTitle').value;
    const price = parseInt(document.getElementById('servicePrice').value);
    const description = document.getElementById('serviceDescription').value;
    
    const newService = {
        id: services.length + 1,
        title,
        price,
        provider: currentUser.displayName || 'Anonymous',
        description,
        category: 'New',
        image: 'new'
    };
    
    // Placeholder for Firebase Firestore
    // db.collection('services').add({
    //   ...newService,
    //   providerId: currentUser.uid,
    //   createdAt: firebase.firestore.FieldValue.serverTimestamp()
    // })
    // .then(docRef => {
    //   newService.id = docRef.id;
    //   services.unshift(newService);
    //   renderServices();
    //   closeModal(addServiceModal);
    //   e.target.reset();
    // })
    // .catch(error => {
    //   console.error('Add service error:', error);
    //   alert('Error adding service:');
    // });
    
    // Mock add service for demo
    services.unshift(newService);
    renderServices();
    closeModal(addServiceModal);
    e.target.reset();
    
    alert(`Service "${title}" added successfully!`);
}

// Update UI based on auth state
function updateUI() {
    if (currentUser) {
        // Update login button to show user info
        loginBtn.textContent = currentUser.displayName || currentUser.email;
        loginBtn.onclick = () => handleLogout();
        
        // Show add service button for providers
        if (currentUser.role === 'provider') {
            becomeProviderBtn.textContent = 'Add Service';
        }
    } else {
        // Reset to original state
        loginBtn.textContent = 'Sign In';
        loginBtn.onclick = () => openModal(loginModal);
        becomeProviderBtn.textContent = 'Become Provider';
    }
}

// Handle logout
function handleLogout() {
    // Placeholder for Firebase auth
    // auth.signOut()
    //   .then(() => {
    //     currentUser = null;
    //     updateUI();
    //   });
    
    // Mock logout for demo
    currentUser = null;
    updateUI();
    console.log('Logged out');
}

// Utility functions
function formatPrice(price) {
    return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 0
    }).format(price / 40); // Convert UAH to USD (approximate)
}

function debounce(func, wait) {
    let timeout;
    return function executedFunction(...args) {
        const later = () => {
            clearTimeout(timeout);
            func(...args);
        };
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
    };
}

// Search and Filter Functions
function handleSearch(e) {
    const query = e.target.value.toLowerCase();
    currentFilters.search = query;
    applyFilters();
}

function handleCategoryFilter(e) {
    const category = e.target.value;
    currentFilters.category = category;
    applyFilters();
}

function applyFilters() {
    filteredServices = services.filter(service => {
        const matchesSearch = currentFilters.search === '' || 
            service.title.toLowerCase().includes(currentFilters.search) ||
            service.description.toLowerCase().includes(currentFilters.search) ||
            service.provider.toLowerCase().includes(currentFilters.search);
        
        const matchesCategory = currentFilters.category === 'all' || 
            service.category === currentFilters.category;
        
        return matchesSearch && matchesCategory;
    });
    
    updateActiveFilters();
    renderFilteredServices(filteredServices);
}

function updateActiveFilters() {
    const filterTags = [];
    
    if (currentFilters.search) {
        filterTags.push(createFilterTag('search', `Search: "${currentFilters.search}"`));
    }
    
    if (currentFilters.category !== 'all') {
        filterTags.push(createFilterTag('category', `Category: ${currentFilters.category}`));
    }
    
    if (filterTags.length > 0) {
        activeFilters.innerHTML = filterTags.join('');
        activeFilters.classList.remove('hidden');
    } else {
        activeFilters.innerHTML = '';
        activeFilters.classList.add('hidden');
    }
}

function createFilterTag(type, text) {
    return `
        <span class="inline-flex items-center gap-2 px-3 py-1 bg-blue-500/20 border border-blue-500/30 rounded-full text-sm">
            ${text}
            <button type="button" class="hover:text-blue-300" onclick="removeFilter('${type}')">
                <i data-lucide="x" class="w-3 h-3"></i>
            </button>
        </span>
    `;
}

function removeFilter(type) {
    if (type === 'search') {
        searchInput.value = '';
        currentFilters.search = '';
    } else if (type === 'category') {
        categoryFilter.value = 'all';
        currentFilters.category = 'all';
    }
    applyFilters();
}

function clearAllFilters() {
    searchInput.value = '';
    categoryFilter.value = 'all';
    currentFilters = {
        search: '',
        category: 'all'
    };
    applyFilters();
}

function renderFilteredServices(filteredServices) {
    if (!servicesGrid) return;
    
    if (filteredServices.length === 0) {
        servicesGrid.classList.add('hidden');
        noResults.classList.remove('hidden');
    } else {
        servicesGrid.classList.remove('hidden');
        noResults.classList.add('hidden');
        servicesGrid.innerHTML = '';
        
        filteredServices.forEach(service => {
            const serviceCard = createServiceCard(service);
            servicesGrid.appendChild(serviceCard);
        });
    }
    
    // Reinitialize Lucide icons
    lucide.createIcons();
}

// Smooth scroll for anchor links
document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
        e.preventDefault();
        const target = document.querySelector(this.getAttribute('href'));
        if (target) {
            target.scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
        }
    });
});

// Add scroll effects
window.addEventListener('scroll', debounce(() => {
    const navbar = document.querySelector('nav');
    if (window.scrollY > 100) {
        navbar.classList.add('scrolled');
    } else {
        navbar.classList.remove('scrolled');
    }
}, 100));

// Add loading states
function showLoading(element) {
    element.classList.add('loading');
    element.disabled = true;
}

function hideLoading(element) {
    element.classList.remove('loading');
    element.disabled = false;
}

// Error handling
function handleError(error, message = 'An error occurred') {
    console.error(error);
    alert(message + ': ' + error.message);
}

// Success notifications
function showSuccess(message) {
    // Create a simple notification (could be enhanced with a toast library)
    const notification = document.createElement('div');
    notification.className = 'fixed top-4 right-4 bg-green-500 text-white px-6 py-3 rounded-lg shadow-lg z-50';
    notification.textContent = message;
    document.body.appendChild(notification);
    
    setTimeout(() => {
        notification.remove();
    }, 3000);
}

// Initialize tooltips and other interactive elements
function initializeInteractions() {
    // Add hover effects to cards
    document.querySelectorAll('.service-card').forEach(card => {
        card.addEventListener('mouseenter', () => {
            card.style.transform = 'translateY(-8px)';
        });
        
        card.addEventListener('mouseleave', () => {
            card.style.transform = 'translateY(0)';
        });
    });
}

// Call initialization
initializeInteractions();
